- name: macOS setup
  hosts: localhost
  become: false
  vars:
    upgrade_homebrew_packages: false
    brew_cask_packages:
      - adobe-acrobat-reader
      - alfred
      - appcleaner
      - box-drive
      - calibre
      - dbeaver-community
      - docker
      - firefox
      - gitkraken
      - google-chrome
      - google-drive
      - gpg-suite
      - intellij-idea-ce
      - iterm2
      - keepassx
      - keka
      - lastpass
      - microsoft-office
      - microsoft-teams
      - offset-explorer
      - openconnect-gui
      - postman
      - protonvpn
      - robo-3t
      - sourcetree
      - spotify
      - sublime-text
      - tor-browser
      - transmit
      - vagrant
      - vagrant-manager
      - virtualbox
      - virtualbox-extension-pack
      - visual-studio-code
      - vlc
    brew_packages:
      - ansible
      - awscli
      - curl
      - git
      - git-lfs
      - jenv
      - jq
      - nvm
      - openssl
      - pyenv
      - pyenv-virtualenv
      - python
      - rbenv
      - ruby-build
      - ssh-copy-id
      - tree
      - wget
      - zsh
      - zsh-syntax-highlighting

  pre_tasks:
    - name: Check if Homebrew is installed
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check

    - name: Fail if Homebrew is not installed
      fail:
        msg: Homebrew is missing... Install from http://brew.sh/
      when: not homebrew_check.stat.exists

  tasks:
    - name: Update Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists

    - name: Upgrade Homebrew packages
      homebrew:
        upgrade_all: "{{ upgrade_homebrew_packages }}"
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Install or upgrade Homebrew cask packages
      homebrew_cask:
        name: "{{ item }}"
        state: latest
      loop: "{{ brew_cask_packages }}"

    - name: Install or upgrade Homebrew packages
      homebrew:
        name: "{{ item }}"
        state: latest
      loop: "{{ brew_packages }}"
