---
- name: macOS setup
  hosts: localhost
  become: false
  #--------------------------------------------------------------------------------
  #--------------------------------------------------------------------------------
  #--------------------------------------------------------------------------------
  vars:
    upgrade_homebrew_packages: false
    brew_cask_packages:
      - adobe-acrobat-reader
      - alfred
      - appcleaner
      - box-drive
      - calibre
      - dbeaver-community
      - docker
      - firefox
      - gitkraken
      - google-chrome
      - google-drive
      - gpg-suite
      - intellij-idea-ce
      - iterm2
      - keepassx
      - keka
      - lastpass
      - microsoft-office
      - microsoft-teams
      - offset-explorer
      - openconnect-gui
      - postman
      - protonvpn
      - robo-3t
      - sourcetree
      - spotify
      - sublime-text
      - tor-browser
      - transmit
      - vagrant
      - vagrant-manager
      - virtualbox
      - virtualbox-extension-pack
      - visual-studio-code
      - vmware-fusion
    brew_packages:
      - awscli
      - curl
      - ansible
      - autoconf
      - bash-completion
      - boot2docker
      - consul
      - docker-compose
      - doxygen
      - git
      - git-lfs
      - go
      - jenv
      - jq
      - nmap
      - nomad
      - nvm
      - openssl
      - packer
      - pyenv
      - pyenv-virtualenv
      - python
      - rbenv
      - ruby-build
      - ssh-copy-id
      - terraform
      - terraform-inventory
      - tmux
      - tree
      - vault
      - wget
      - zsh
      - zsh-syntax-highlighting
  #--------------------------------------------------------------------------------
  #--------------------------------------------------------------------------------
  #--------------------------------------------------------------------------------
  pre_tasks:
    #  Check Homebrew Is Installed
    - name: Check Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    # Fail If Homebrew Is Not Installed
    - name: Fail If Homebrew Is Not Installed.
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when:
        - not homebrew_check.stat.exists
  #--------------------------------------------------------------------------------
  #--------------------------------------------------------------------------------
  #--------------------------------------------------------------------------------
  tasks:
    # Update Homebrew
    - name: Update Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists

    # Upgrade Homebrew Packages
    - name: Upgrade Homebrew Packages
      homebrew:
        upgrade_all: "{{ upgrade_homebrew_packages }}"
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    # Install Homebrew Cask Packages
    - name: Install Homebrew Cask Packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    # Install Homebrew Packages
    - name: Install Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists
